[package]
name = "mock-alb-oidc-rs"
version = "0.1.0"
authors = ["Jonathan K. Wolski <jonwolski@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oidc = "0.3.0"
actix-web = "1.0.8"
